# Name(s)
Erik Christensen,
Jack Langston

**Instructions:** This is an individual assignment, but you may discuss your code with your neighbors.

# Python and NumPy

While other IDEs exist for Python development and for data science related activities, one of the most popular environments is Jupyter Notebooks.

This lab is not intended to teach you everything you will use in this course. Instead, it is designed to give you exposure to some critical components from NumPy that we will rely upon routinely.

## Exercise 0
Please read and reference the following as your progress through this course. 

* [What is the Jupyter Notebook?](https://nbviewer.jupyter.org/github/jupyter/notebook/blob/master/docs/source/examples/Notebook/What%20is%20the%20Jupyter%20Notebook.ipynb#)
* [Notebook Tutorial](https://www.datacamp.com/community/tutorials/tutorial-jupyter-notebook)
* [Notebook Basics](https://nbviewer.jupyter.org/github/jupyter/notebook/blob/master/docs/source/examples/Notebook/Notebook%20Basics.ipynb)

**In the space provided below, what are three things that still remain unclear or need further explanation?**

1. Which folders are shared and which are not

2. All the little tricks you can do in markdown

3. Shortcuts that can be done in Jupyter

## Exercises 1-7
For the following exercises please read the Python appendix in the Marsland textbook and answer problems A.1-A.7 in the space provided below.

## Exercise 1

In [18]:
# YOUR SOLUTION HERE
import numpy as np
a = np.ones((6, 4), dtype=int)*2

print(a) 

[[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]


## Exercise 2

In [19]:
# YOUR SOLUTION HERE
b = np.ones((6, 4), dtype=int)
b[range(4), range(4)] = 3
print(b) 

[[3 1 1 1]
 [1 3 1 1]
 [1 1 3 1]
 [1 1 1 3]
 [1 1 1 1]
 [1 1 1 1]]


## Exercise 3

You can do a*b because it returns the product of the two numbers from the same indices in each location in the new array.
We cannot use the dot function because we cannot multiply the two matrices together since a 6x4 cannot be multiplied by a 6x4 since 4 does not equal 6.

In [3]:
print("a*b:")
print(a*b)

try:
    np.dot(a, b)
except:
    print("The dot did not work")

a*b:
[[6 2 2 2]
 [2 6 2 2]
 [2 2 6 2]
 [2 2 2 6]
 [2 2 2 2]
 [2 2 2 2]]
The dot did not work


## Exercise 4

In [4]:
print("a.T dot b")
print(np.dot(a.transpose(), b))
print(' ')
print("a dot b.T")
print(np.dot(a, b.transpose()))

a.T dot b
[[16 16 16 16]
 [16 16 16 16]
 [16 16 16 16]
 [16 16 16 16]]
 
a dot b.T
[[12 12 12 12  8  8]
 [12 12 12 12  8  8]
 [12 12 12 12  8  8]
 [12 12 12 12  8  8]
 [12 12 12 12  8  8]
 [12 12 12 12  8  8]]


a.T dot b is 4x4 because a 4x6 dot 6x4 makes a 4x4 matrix. a dot b.T is 6x6 because a 6x4 dot 4x6 makes a 6x6 matrix. We find the sizes using the number of columns in the first matrix by the rows in the second column.

## Exercise 5

In [5]:
def squarer(num):
    for i in range(num+1):
        print(i*i)
squarer(10)

0
1
4
9
16
25
36
49
64
81
100


## Exercise 6

In [6]:
def random_arrays(low, high):
    for i in range(3):
        rows = np.random.randint(low, high)
        cols = np.random.randint(low, high)
        a = np.array([[np.random.randint(low, high) for i in range(rows)] for j in range(cols)])
        print(a)
        print("Sum: %d"%np.sum(a))
        print("Mean: %f"%np.mean(a))
        print("")

random_arrays(5, 15)

[[ 6 12 14 14 14  8 13  9  7]
 [ 7 12  5 12 13  7  5  5 10]
 [ 8 14 11  8 14 12 10  7  6]
 [ 8 11 10  8  8 14  5  6  9]
 [10 11 10 11 10  7  7  5  9]
 [12 10  6  8  7  5  9 12  8]
 [ 6  9  8  8  7  6  8  6  9]
 [11 13 13 10 11  5 11  7  8]
 [11  8  6 11 12  7 11 11  6]
 [ 9 11  7  9  9  6  8  6 11]
 [13 10  9  6 12  8  8 12 10]
 [ 9 11 14  5 10  5 13 10  5]
 [12 13 14 12 14 13 14  6 10]
 [11  9 11 11  7 11 10  8  5]]
Sum: 1175
Mean: 9.325397

[[12 12 13 13  5 11  9 11 13  7]
 [ 6  5 14  7  5 13  5 13 14  9]
 [10  7 12  7  6  8  9 10 14  5]
 [10 13  6 11  7 14  7 11  9  9]
 [ 8 10 11  6 12 11  5 10  6  9]
 [ 7 14  6  5  6 13 13  7  9 11]
 [12  7 12  6 13 14 10 12  5 11]
 [ 7 10 14 10  7  9  9  6  9  8]
 [ 8  8  5  7  5 14  9 11  5  5]
 [13  9 11  7 13  9  6 10  6  6]
 [ 9 12  6  6 10 13  8 10  6 11]
 [14  6 11  8 12 13 12  5  9  5]]
Sum: 1105
Mean: 9.208333

[[11 11 10  5  7 14 13 11  8]
 [11  7  5  7 12  8  8  8 11]
 [13 10  7  6 11 12  9  8 10]
 [12  6 12  9  9  9  8 10 10]
 [ 5  7  7

## Exercise 7

In [7]:
def random_array(low, high):
    rows = np.random.randint(low, high)
    cols = np.random.randint(low, high)
    a = np.array([[np.random.randint(low, high) for i in range(rows)] for j in range(cols)])
    print(a)
    return a

def one_counter(array):
    count = 0
    for i in range(array.shape[0]):
        for j in range(array.shape[1]):
            if array[i][j] == 1:
                count += 1
    print(count)
    
def one_counter2(array):
    print(np.where(array == 1, 1, 0).sum().sum())
    
arr = random_array(1,6)
one_counter(arr)
one_counter2(arr)

[[5 5 3 5 5]
 [4 3 5 5 1]
 [4 5 2 1 3]]
2
2


## Excercises 8-???
While the Marsland book avoids using another popular package called Pandas, we will use it at times throughout this course. Please read and study [10 minutes to Pandas](https://pandas.pydata.org/pandas-docs/stable/getting_started/10min.html) before proceeding to any of the exercises below.

## Exercise 8
Repeat exercise A.1 from Marsland, but create a Pandas DataFrame instead of a NumPy array.

In [8]:
import pandas as pd
a_df = pd.DataFrame([[2 for i in range(4)] for j in range(6)])
a_df

0  1  2  3
0  2  2  2  2
1  2  2  2  2
2  2  2  2  2
3  2  2  2  2
4  2  2  2  2
5  2  2  2  2

## Exercise 9
Repeat exercise A.2 using a DataFrame instead.

In [9]:
b_df = pd.DataFrame([[1 for i in range(4)] for j in range(6)])
for i in range(4):
    b_df.at[i,i] = 3
b_df

0  1  2  3
0  3  1  1  1
1  1  3  1  1
2  1  1  3  1
3  1  1  1  3
4  1  1  1  1
5  1  1  1  1

## Exercise 10
Repeat exercise A.3 using DataFrames instead.

In [10]:
print("a_df * b_df:\n")
display(a_df * b_df)

print("Attempting to dot:")
try:
    a_df.dot(b_df)
except Exception as e:
    print(e)

a_df * b_df:



0  1  2  3
0  6  2  2  2
1  2  6  2  2
2  2  2  6  2
3  2  2  2  6
4  2  2  2  2
5  2  2  2  2

Attempting to dot:
matrices are not aligned


## Exercise 11
Repeat exercise A.7 using a dataframe.

In [11]:
def random_df(low, high):
    rows = np.random.randint(low, high)
    cols = np.random.randint(low, high)
    a = pd.DataFrame([[np.random.randint(low, high) for i in range(rows)] for j in range(cols)])
    display(a)
    return a

def one_counter(df):
    count = 0
    for i in range(df.shape[0]):
        for j in range(df.shape[1]):
            if df.at[i, j] == 1:
                count += 1
    print(count)
    
def one_counter2(df):
    print((df == 1).sum().sum())
    
df = random_df(1,6)
one_counter(df)
one_counter2(df)

0  1  2
0  4  2  3
1  5  2  2

0
0


## Exercises 12-14
Now let's look at a real dataset, and talk about ``.loc``. For this exercise, we will use the popular Titanic dataset from Kaggle. Here is some sample code to read it into a dataframe.

In [12]:
titanic_df = pd.read_csv(
    "https://raw.githubusercontent.com/dlsun/data-science-book/master/data/titanic.csv"
)
titanic_df

pclass  survived                                             name  \
0          1         1                    Allen, Miss. Elisabeth Walton   
1          1         1                   Allison, Master. Hudson Trevor   
2          1         0                     Allison, Miss. Helen Loraine   
3          1         0             Allison, Mr. Hudson Joshua Creighton   
4          1         0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)   
...      ...       ...                                              ...   
1304       3         0                             Zabour, Miss. Hileni   
1305       3         0                            Zabour, Miss. Thamine   
1306       3         0                        Zakarian, Mr. Mapriededer   
1307       3         0                              Zakarian, Mr. Ortin   
1308       3         0                               Zimmerman, Mr. Leo   

         sex      age  sibsp  parch  ticket      fare    cabin embarked boat  \
0     female  29.0000      0      0   24160  211.3375       B5        S    2   
1       male   0.9167      1      2  113781  151.5500  C22 C26        S   11   
2     female   2.0000      1      2  113781  151.5500  C22 C26        S  NaN   
3       male  30.0000      1      2  113781  151.5500  C22 C26        S  NaN   
4     female  25.0000      1      2  113781  151.5500  C22 C26        S  NaN   
...      ...      ...    ...    ...     ...       ...      ...      ...  ...   
1304  female  14.5000      1      0    2665   14.4542      NaN        C  NaN   
1305  female      NaN      1      0    2665   14.4542      NaN        C  NaN   
1306    male  26.5000      0      0    2656    7.2250      NaN        C  NaN   
1307    male  27.0000      0      0    2670    7.2250      NaN        C  NaN   
1308    male  29.0000      0      0  315082    7.8750      NaN        S  NaN   

       body                        home.dest  
0       NaN                     St Louis, MO  
1       NaN  Montreal, PQ / Chesterville, ON  
2       NaN  Montreal, PQ / Chesterville, ON  
3     135.0  Montreal, PQ / Chesterville, ON  
4       NaN  Montreal, PQ / Chesterville, ON  
...     ...                              ...  
1304  328.0                              NaN  
1305    NaN                              NaN  
1306  304.0                              NaN  
1307    NaN                              NaN  
1308    NaN                              NaN  

[1309 rows x 14 columns]

Notice how we have nice headers and mixed datatypes? That is one of the reasons we might use Pandas. Please refresh your memory by looking at the 10 minutes to Pandas again, but then answer the following.

## Exercise 12
How do you select the ``name`` column without using .iloc?

In [13]:
titanic_df["name"]

0                         Allen, Miss. Elisabeth Walton
1                        Allison, Master. Hudson Trevor
2                          Allison, Miss. Helen Loraine
3                  Allison, Mr. Hudson Joshua Creighton
4       Allison, Mrs. Hudson J C (Bessie Waldo Daniels)
                             ...                       
1304                               Zabour, Miss. Hileni
1305                              Zabour, Miss. Thamine
1306                          Zakarian, Mr. Mapriededer
1307                                Zakarian, Mr. Ortin
1308                                 Zimmerman, Mr. Leo
Name: name, Length: 1309, dtype: object

## Exercise 13
After setting the index to ``sex``, how do you select all passengers that are ``female``? And how many female passengers are there?

In [14]:
## We can use .loc["female"] to find the number of females and we can see that there are 466 of them
titanic_df.set_index('sex',inplace=True)
titanic_df.loc["female"]

pclass  survived                                             name  \
sex                                                                         
female       1         1                    Allen, Miss. Elisabeth Walton   
female       1         0                     Allison, Miss. Helen Loraine   
female       1         0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)   
female       1         1                Andrews, Miss. Kornelia Theodosia   
female       1         1    Appleton, Mrs. Edward Dale (Charlotte Lamson)   
...        ...       ...                                              ...   
female       3         1  Whabee, Mrs. George Joseph (Shawneene Abi-Saab)   
female       3         1                 Wilkes, Mrs. James (Ellen Needs)   
female       3         1          Yasbeck, Mrs. Antoni (Selini Alexander)   
female       3         0                             Zabour, Miss. Hileni   
female       3         0                            Zabour, Miss. Thamine   

         age  sibsp  parch  ticket      fare    cabin embarked boat   body  \
sex                                                                          
female  29.0      0      0   24160  211.3375       B5        S    2    NaN   
female   2.0      1      2  113781  151.5500  C22 C26        S  NaN    NaN   
female  25.0      1      2  113781  151.5500  C22 C26        S  NaN    NaN   
female  63.0      1      0   13502   77.9583       D7        S   10    NaN   
female  53.0      2      0   11769   51.4792     C101        S    D    NaN   
...      ...    ...    ...     ...       ...      ...      ...  ...    ...   
female  38.0      0      0    2688    7.2292      NaN        C    C    NaN   
female  47.0      1      0  363272    7.0000      NaN        S  NaN    NaN   
female  15.0      1      0    2659   14.4542      NaN        C  NaN    NaN   
female  14.5      1      0    2665   14.4542      NaN        C  NaN  328.0   
female   NaN      1      0    2665   14.4542      NaN        C  NaN    NaN   

                              home.dest  
sex                                      
female                     St Louis, MO  
female  Montreal, PQ / Chesterville, ON  
female  Montreal, PQ / Chesterville, ON  
female                       Hudson, NY  
female              Bayside, Queens, NY  
...                                 ...  
female                              NaN  
female                              NaN  
female                              NaN  
female                              NaN  
female                              NaN  

[466 rows x 13 columns]

## Exercise 14
How do you reset the index?

In [20]:
# We can use the .reset_index() command 

titanic_df.reset_index(inplace=True)